[WIP] 6-save-data-in-db
yuka-dir/mercari-build-hackthon-team2 pull request #10
Opened 2022-05-26 09:47 UTC by nsmryk

## What

## Test

## CHECKS :warning:

Please make sure you are aware of the following.

- [ ] **The changes in this PR doesn't have private information

2022-05-26 13:23 UTC, yuka-dir requested changes
この状態でフロントエンドは動く、と言ってしまったのですが、すみません動きません。
追加で、以下の商品の詳細情報を取得するエンドポイントが欲しいです（[STEP3-7 ](https://github.com/yuka-dir/mercari-build-training-2022/blob/main/document/step3.ja.md#:~:text=%E3%81%BF%E3%81%BE%E3%81%97%E3%82%87%E3%81%86-,7.%20%E5%95%86%E5%93%81%E3%81%AE%E8%A9%B3%E7%B4%B0%E3%82%92%E8%BF%94%E3%81%99,-%E5%95%86%E5%93%81%E3%81%AE%E8%A9%B3%E7%B4%B0)）！
`GET /items/<item_id>`

2022-05-26 13:23 UTC, yuka-dir commented on python/main.py
> +    filepath = f"../images/{image_filename}"
リクエスト
```
curl -X POST \
--url 'http://localhost:9000/items' \
  -F 'name=jacket' \
  -F 'category_id=fashion' \
  -F 'image=@./images/default.jpg'
```
エラーが出ます。
```
  File "./main.py", line 78, in add_item
    with open(filepath, "w+b") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../images/cd6357efdd966de8c0cb2f876cc89ec74ce35f0968e11743987084bd42fb8944.jpg'
```

```suggestion
    filepath = f"./images/{image_filename}"
```
もしくは
```suggestion
    filepath = f"images/{image_filename}"
```
 かなと思います！

2022-05-26 13:23 UTC, uukait commented on python/main.py
> +            with open('../db/items.db') as f:
このブランチに`db/items.db`が存在しないので、エラーが出てしまいます。
すみません、自分のミスです。`main`ブランチを更新したので、一度このブランチに`main`の更新を取り込んでいただきたいです🙇‍♂️

2022-05-26 13:51 UTC, nsmryk commented on python/main.py
> +    filepath = f"../images/{image_filename}"
修正しました。

2022-05-26 14:00 UTC, nsmryk commented on python/main.py
> +            with open('../db/items.db') as f:
こちらこそ追加漏れしてました！
追加しましたが動作しますか？

2022-05-26 14:13 UTC, yuka-dir commented on python/main.py
> +    filepath = f"../images/{image_filename}"
3e612c845a842946ae0baa155ce498563c93aa3bで修正が確認できました！

2022-05-26 14:24 UTC, yuka-dir commented on python/main.py
> +            with open('../db/items.db') as f:
追加ありがとうございます！！！

items.dbに合わせて、main.pyの中の`category_id`を全て`category`に変更が必要ですね。

2022-05-27 07:08 UTC, nsmryk commented on python/main.py
> +            with open('../db/items.db') as f:
失礼しました！修正しておきました。

2022-05-27 08:08 UTC, yuka-dir approved these changes
動作確認OKです！

2022-05-27 08:08 UTC, yuka-dir commented on python/main.py
> +            with open('../db/items.db') as f:
d08c6aa92f6784afefe82a7c8f2ec044c8599892 で修正されていることが確認できました！
ありがとうございます！

2022-05-27 08:11 UTC, merged